version: "3"

services:
  pg:
    image: postgres:9.6-alpine
    ports:
      - '5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
